import { FEEDBACK_SEVERITY_LABEL } from "@/lib/audit/feedback";

/** Column headers used by audit CSV export — import accepts the same layout. */
export const FIXED_EXPORT_HEADERS = [
  "Audit ID",
  "Template",
  "Agent",
  "Supervisor",
  "Quality analyst",
  "Interaction type",
  "Audit type",
  "Business type",
  "LOB",
  "Sub-LOB",
  "Reason",
  "Sub-reason (DFF)",
  "Call date",
  "Audit date",
  "Contact (number / name)",
  "Reference",
  "Response",
  "Quality %",
  "Final %",
  "Grade",
  "Has fatal",
  "Fatal parameters",
  "Points scored",
  "Points max",
  "Category scores",
  "Parameter summary",
  FEEDBACK_SEVERITY_LABEL,
  "Feedback status",
  "Feedback date",
  "Acknowledged / disputed at",
  "Feedback for agent",
  "Supervisor remarks",
  "Submitted by",
  "Submitted at",
] as const;
